#!/usr/bin/env python3
"""Print a weekly Markdown digest from data/articles.json for Substack / LinkedIn paste.

Usage:
  python scripts/digest.py
  python scripts/digest.py --days 7 --limit 12
  python scripts/digest.py --out digest.md
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ARTICLES_PATH = ROOT / "data" / "articles.json"

CATEGORY_LABELS = {
    "medical-device": "Medical devices",
    "ai-in-health": "AI in health",
    "wellness-tech": "Wellness tech",
    "fitness-tech": "Fitness tech",
    "other": "Other",
}

COUNTRY_LABELS = {
    "GLOBAL": "Global",
    "IN": "India",
    "US": "United States",
    "CN": "China",
    "GB": "United Kingdom",
    "DE": "Germany",
    "JP": "Japan",
}

FEATURED_ORDER = ("GLOBAL", "IN", "US", "CN", "GB", "DE", "JP")


def parse_dt(raw: str | None) -> datetime | None:
    if not raw:
        return None
    try:
        return datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except ValueError:
        return None


def main() -> int:
    parser = argparse.ArgumentParser(description="Weekly Markdown digest for newsletters")
    parser.add_argument("--days", type=int, default=7, help="Lookback window in days")
    parser.add_argument("--limit", type=int, default=15, help="Max articles to include")
    parser.add_argument("--out", type=str, default="", help="Optional output file path")
    parser.add_argument(
        "--substack-url",
        type=str,
        default="",
        help="Substack URL to mention in the intro (optional)",
    )
    args = parser.parse_args()

    with ARTICLES_PATH.open(encoding="utf-8") as f:
        data = json.load(f)
    articles = list(data.get("articles") or [])

    cutoff = datetime.now(timezone.utc) - timedelta(days=args.days)
    recent = []
    for a in articles:
        dt = parse_dt(a.get("published_at") or a.get("ingested_at"))
        if dt is None or dt >= cutoff:
            recent.append(a)
    recent.sort(key=lambda a: a.get("published_at") or "", reverse=True)
    recent = recent[: args.limit]

    week_label = datetime.now(timezone.utc).strftime("%B %d, %Y")
    lines: list[str] = [
        f"# Your Health Tech Guy — Weekly Digest ({week_label})",
        "",
        "A free roundup of health & technology headlines. Summaries are original; "
        "click through for the full story at the publisher.",
        "",
    ]
    if args.substack_url:
        lines.extend([f"Subscribe: {args.substack_url}", ""])

    if not recent:
        lines.append("_No articles in this window._")
    else:
        by_country: dict[str, list] = {}
        for a in recent:
            code = a.get("country") or "OTHER"
            by_country.setdefault(code, []).append(a)

        lines.append("## By region")
        lines.append("")
        for code in FEATURED_ORDER:
            items = by_country.pop(code, [])
            if not items:
                continue
            label = COUNTRY_LABELS.get(code, code)
            lines.append(f"### {label}")
            lines.append("")
            for a in items:
                title = a.get("title") or "Untitled"
                url = a.get("url") or "#"
                source = a.get("source") or "Source"
                summary = (a.get("summary") or "").strip()
                cat = CATEGORY_LABELS.get(a.get("category") or "", a.get("category") or "")
                lines.append(f"**[{title}]({url})** — {source}" + (f" · {cat}" if cat else ""))
                if summary:
                    lines.append("")
                    lines.append(summary)
                lines.append("")

        # Remaining countries
        for code in sorted(by_country.keys()):
            items = by_country[code]
            if not items:
                continue
            label = COUNTRY_LABELS.get(code, code)
            lines.append(f"### {label}")
            lines.append("")
            for a in items:
                title = a.get("title") or "Untitled"
                url = a.get("url") or "#"
                source = a.get("source") or "Source"
                summary = (a.get("summary") or "").strip()
                lines.append(f"**[{title}]({url})** — {source}")
                if summary:
                    lines.append("")
                    lines.append(summary)
                lines.append("")

    lines.extend(
        [
            "---",
            "",
            "_Generated by Your Health Tech Guy. Paste into Substack or LinkedIn Newsletter and edit as needed._",
            "",
        ]
    )

    text = "\n".join(lines)
    if args.out:
        Path(args.out).write_text(text, encoding="utf-8")
        print(f"Wrote {args.out}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
